%[shared/server.yml]

dataExpiryThreadhold: 3
cacheFolder: data/cache

inMemoryGraph: false
graphDBConfig:
  graphName: databases/tramchester.db
  neo4jPagecacheMemory: 100m
  memoryTransactionGlobalMaxSize: 650m
  enableDiagnostics: ${ENABLE_DB_DIAG:- false }

%[shared/tfgm_trams.yml]
planningEnabled: false
%[shared/tfgm_tram_planning.yml]

%[shared/infra.yml]

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: INFO
    - type: file
      currentLogFilename: logs/fetch_data.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/fetch_data_%i.log
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 50MB
