%[shared/server.yml]

inMemoryGraph: true
#graphDBConfig:
#  graphName: databases/tramchester.db
#  neo4jPagecacheMemory: 100m
#  memoryTransactionGlobalMaxSize: 650m
#  enableDiagnostics: ${ENABLE_DB_DIAG:- false }

cacheFolder: data/cache
dataExpiryThreadhold: 3

%[shared/tfgm_trams.yml]
%[shared/tfgm_live_data.yml]
planningEnabled: true
%[shared/tfgm_tram_planning.yml]

%[shared/infra.yml]

logging:
  level: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: file
      currentLogFilename: logs/tramchester_local.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_local_%i.log
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 50MB
