tfgmTramliveData:
  dataUrl: ${LIVEDATA_URL:- "sns://tramchester_live_data_ProdBlue"}
  dataSubscriptionKey: ${TFGMAPIKEY:- ""}
  s3Bucket: ""
  s3Prefix: ${PLACE:- "test"}
  refreshPeriodSeconds: 20
  maxNumberStationsWithoutMessages: 10
  maxNumberStationsWithoutData: 5
  snsTopicPrefix: tramchester_live_data_