gtfsSourceConfig:
  - name: tfgm
    hasFeedInfo: false
    transportModes: [ tram ]
    transportModesWithPlatforms: [ Tram ]
    initialWaitMinutes: 13
    noServices: []
    markedInterchangesOnly: false
    additionalInterchanges: []
    groupedStationModes: []
    addWalksForClosed: true
    stationClosures: []
    temporaryStationsWalks: []
remoteSources:
  - name: tfgm
    dataURL: ${TRAM_DATAURL:- s3://tramchesternewdist/dist/${RELEASE_NUMBER}/tfgm_data.zip}
    dataCheckURL: https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip
    dataPath: data/tram/TfGMgtfs
    downloadPath: data/tram
    filename: tfgm_data.zip
    defaultExpiryDays: 1
  - name: database
    skip:
      config: inMemoryGraph
    dataURL: s3://tramchesternewdist/dist/${RELEASE_NUMBER}/database.zip
    dataCheckURL: s3://tramchesternewdist/dist/${RELEASE_NUMBER}/database.zip
    dataPath: databases
    downloadPath: databases
    filename: database.zip
    defaultExpiryDays: 0
    modTimeCheckFilename: tramchester.db
    mandatory: false
    skipUpload: false
bounds:
  minEastings: 333200
  minNorthings: 373130
  maxEasting: 414500
  maxNorthings: 437850